wandb_version: 1

BIO:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.21.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1659291528
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.10.4
      5: 0.12.21
      6: 4.21.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 5
experiment:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
max_len:
  desc: null
  value: 128
